name: ЁЯОм Toffee Auto Playlist Builder

on:
  schedule:
    - cron: "0 */6 * * *"    # ржкрзНрж░рждрж┐ рзм ржШржгрзНржЯрж╛рзЯ ржЕржЯрзЛ рж░рж╛ржи (ржмрж╛ржВрж▓рж╛ржжрзЗрж╢ рж╕ржорзЯ ржЕржирзБржпрж╛рзЯрзА)
  workflow_dispatch: {}       # ржЪрж╛ржЗрж▓рзЗ ржорзНржпрж╛ржирзБрзЯрж╛рж▓рж┐ рж░рж╛ржи ржХрж░рж╛ ржпрж╛ржмрзЗ

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ЁЯУж Checkout repository
        uses: actions/checkout@v4

      - name: ЁЯРН Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: ЁЯУж Install dependencies
        run: pip install requests

      - name: тЦ╢я╕П Run Toffee Script
        env:
          TOFFEE_JWT: ${{ secrets.TOFFEE_JWT }}
        run: python toffee_play.py

      - name: ЁЯТ╛ Commit and Push Playlist
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add toffee_channels.m3u
          git commit -m "ЁЯФД Auto updated Toffee playlist"
          git push
